version: '3'

services:
  db:
    image: 'mysql:5.7'
    container_name: mysql.container.cl
    ports:
           - "33060:3306"
    environment:
           - MYSQL_ROOT_PASSWORD=almaveloz
           - MYSQL_DATABASE=empleados
           - MYSQL_USER=root
           - MYSQL_PASSWORD=almaveloz
           - MYSQL_ROOT_HOST=%
    volumes:
           - /var/lib/docker/volumes/mysql-data/_data:/var/lib/mysql
    healthcheck:
           test: ["CMD","mysqladmin","ping","-h","mysql.container.cl"]
           timeout: 20s
           retries: 10
    restart: always
  backendserver:
    build: ../../devjava/springboot2-jpa-crud-example/
    container_name: rest-springboot-container
    image: employees_rest_springboot
    command: java -jar app.jar
    ports:
           - "8080:8080"
    links:
           - "db"
    depends_on:
           - "db"
    restart: always
  frontend:
    build: .
    container_name: angular8-web-crud
    image: employees_web_angular
    links:
           - "backendserver"
    depends_on:
           - "backendserver"
    ports:
           - "8001:80"   