version: '2.1'
services: 

  database:
    image: mysql:5.7
    container_name: mysql.container
    volumes:
      - "/var/lib/docker/volumes/mysql-data/_data:/var/lib/mysql"
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'almaveloz'     
    networks: 
      apinetwork:
  web:
    build: .
    container_name: node-rest-container
    command: node server.js
    #volumes:
     # - .:/usr/src/app
    ports:
      - "80:8080"
    networks: 
      apinetwork:

networks:
  apinetwork:
    driver: bridge
    ipam: 
      config: 
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
          aux_addreses:
            database: 172.16.238.2 
# ipam is removed in version 3, issues with swarm mode
# https://github.com/docker/compose/issues/4474     
